name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  # --- JOB 1: Build binaries for all target platforms ---
  build:
    name: Build for ${{ matrix.os }}/${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - os: darwin
            arch: arm64
            runner: ARM64
          - os: linux
            arch: arm64
            runner: ARM64
          - os: linux
            arch: amd64
            runner: AMD64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Install Native Dependencies (Linux AMD64 only)
        if: matrix.os == 'linux' && matrix.arch == 'amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev pkg-config

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build Web UI
        run: |
          cd web
          bun install
          bun run build
          cd ..

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 1
          PKG_CONFIG_PATH: ${{ matrix.os == 'darwin' && '/opt/homebrew/lib/pkgconfig' || '' }}
        run: |
          if [[ "${{ matrix.os }}" == "linux" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "--- Building linux/arm64 via Docker ---"
            docker run --rm --platform linux/arm64 \
              -v "$PWD":/src \
              -w /src \
              debian:bullseye \
              bash -c ' \
                set -e && \
                export DEBIAN_FRONTEND=noninteractive && \
                apt-get update && \
                apt-get install -y build-essential pkg-config libvirt-dev wget && \
                export GO_VERSION="1.25.0" && \
                wget "https://golang.org/dl/go${GO_VERSION}.linux-arm64.tar.gz" && \
                tar -C /usr/local -xzf "go${GO_VERSION}.linux-arm64.tar.gz" && \
                export PATH="/usr/local/go/bin:${PATH}" && \
                echo "--- Compiling Go binary inside container ---" && \
                go mod download && \
                go build -ldflags="-s -w" -o flint . \
              '
          else
            echo "--- Native build for ${{ matrix.os }}/${{ matrix.arch }} ---"
            go build -ldflags="-s -w" -o flint .
          fi

      - name: Package Binary
        run: |
          zip -j flint-${{ matrix.os }}-${{ matrix.arch }}.zip flint

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flint-binary-${{ matrix.os }}-${{ matrix.arch }}
          path: flint-${{ matrix.os }}-${{ matrix.arch }}.zip

  # --- JOB 2: Create the GitHub Release after all builds are done ---
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        # No 'path' property here. This downloads all artifacts from the run
        # into folders named after the artifacts in the current directory.

      - name: Display structure of downloaded files (for debugging)
        run: ls -R

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # The '**' glob recursively finds all .zip files to upload to the release.
          files: "**/*.zip"
